[build]
  base = "/"
  command = "npm run build"
  functions = "build"
  publish = "dist"
  environment = { EXPIRE = "5184000", UID_LENGTH = "4" }
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
[[redirects]]
  from = "/:id"
  to = "/index.html"
  status = 404
