version: '2'
services:
  app:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: tupo.to
      port_rules:
      - hostname: tupo.to
        priority: 1
        protocol: http
        service: app
        source_port: 80
        target_port: 3000
      - hostname: tupo.to
        priority: 2
        protocol: https
        service: app
        source_port: 443
        target_port: 3000
      - hostname: tupo.to
        path: /.well-known/acme-challenge
        priority: 3
        protocol: http
        service: letsencrypt/letsencrypt
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  redis:
    scale: 1
    start_on_create: true
